cfg80211
mac80211
pinctrl-slg51000
pinctrl-slg51002
smra
slg51000-regulator
slg51002-regulator
iovad-vendor-hooks
slg51000-core
slg51002-core
usb_f_etr_miu
stmvl53l1
odpm-whi
pwm-exynos
rt4539_bl
aoc_unit_test_dev
google_dock
google_ccd
max77779-charger-i2c
max77779-vimon
max77779-vimon-i2c
max77779-fg-i2c
max77779-sp
max77779-sp-i2c
max77779_i2cm
max77779_i2cm_i2c
max77779_pmic_irq
max77779_pmic_pinctrl
max77779_pmic_sgpio
max77779_pmic_i2c
ln8411
max77779-fwupdate
rt9471_charger
hl7132
gs-panel
panel-common
janeiro
fps_touch_handler
mali_kutf
mali_kutf_clk_rate_trace_test_portal
mali_kbase
mali_pixel
gxp
lwis
sscoredump_test
sscoredump_sample_test
bigwave
snd-soc-cs35l41-i2c
snd-soc-cs35l45-i2c
cl_dsp-core
cs40l26-core
cs40l26-i2c
snd-soc-cs40l26
nitrous
bbd_pps_gpio
goog_touch_interface
focal_touch
sec_touch
syna_touch
mcps802154
mcps802154_region_fira
mcps802154_region_nfcc_coex
mcps802154_region_pctt
dw3000
dw3000-core-tests
bcmdhd4389
gzvm
kheaders
zsmalloc
libarc4
mii
can-dev
vcan
slcan
ppp_generic
ppp_async
bsd_comp
ppp_deflate
ppp_mppe
ppp_synctty
pppox
pppoe
pptp
slhc
wwan
rtl8150
r8152
asix
ax88179_178a
cdc_ether
cdc_eem
usbnet
cdc_ncm
aqc111
r8153_ecm
cdc-acm
usbserial
ftdi_sio
hci_vhci
hci_uart
btsdio
btbcm
btqca
8021q
can
can-raw
can-bcm
can-gw
bluetooth
rfcomm
hidp
l2tp_core
l2tp_ppp
tipc
diag
rfkill
6lowpan
nhc_dest
nhc_fragment
nhc_hop
nhc_ipv6
nhc_mobility
nhc_routing
nhc_udp
ieee802154_6lowpan
ieee802154
ieee802154_socket
mac802154
nfc
